### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Asandru** [ElunaLuaEngine/Eluna#273]
After merging fresh trinity core with eluna trinitycore wotlk I got these c++ compile errors:

`8>d:\development\elunatrinityserver\trinitycore\src\server\game\luaengine\unitmethods.h(2064): error C2039: 'MovementExpired': is not a member of 'MotionMaster'
8>d:\development\elunatrinityserver\trinitycore\src\server\game\movement\motionmaster.h(98): note: see declaration of 'MotionMaster'
8>d:\development\elunatrinityserver\trinitycore\src\server\game\luaengine\unitmethods.h(2076): error C2664: 'void MotionMaster::Clear(MovementGeneratorPriority)': cannot convert argument 1 from 'bool' to 'MovementSlot'
8>d:\development\elunatrinityserver\trinitycore\src\server\game\luaengine\unitmethods.h(2076): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)
8>d:\development\elunatrinityserver\trinitycore\src\server\game\luaengine\playermethods.h(3308): error C2039: 'MovementExpired': is not a member of 'MotionMaster'
8>d:\development\elunatrinityserver\trinitycore\src\server\game\movement\motionmaster.h(98): note: see declaration of 'MotionMaster'
8>Done building project "game.vcxproj" -- FAILED.
`
