### ISSUE TITLE
Update TC make error

### ISSUE THREAD

**Issue by ConradBunton** [ElunaLuaEngine/Eluna#241]
After merging with the TC, I have that error :
\src\server\game\luaengine\CreatureMethods.h(443): error C2039: 'GetCurrentWaypointID'

I tried to replace GetCurrentWaypointID by GetCurrentWaypointInfo (The new command), but it only make more error. That's come from the commit "Core/Misc: waypoint movement' by CCRS (11.06.2017 10:16 pm).

In the Creature.h, there's that change :
-        uint32 GetCurrentWaypointID() const { return m_waypointID; }
-        void UpdateWaypointID(uint32 wpID) { m_waypointID = wpID; }
+        // nodeId, pathId
+        std::pair<uint32, uint32> GetCurrentWaypointInfo() const { return _currentWaypointNodeInfo; }
+        void UpdateCurrentWaypointInfo(uint32 nodeId, uint32 pathId) { _currentWaypointNodeInfo = { nodeId, pathId }; }

In Creature.cpp :
-            if (m_leader->GetCurrentWaypointID() == itr->second->point_1 - 1 || m_leader->GetCurrentWaypointID() == itr->second->point_2 - 1)
+            if (m_leader->GetCurrentWaypointInfo().first == itr->second->point_1 || m_leader->GetCurrentWaypointInfo().first == itr->second->point_2)

**Comment by Rochet2** [comment]
We get email notifications of these.
Also if you merge to cores then you should fix the merge errors on your own.
